/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Search;

import Controller.ProductController;
import Model.Produk;
import Util.Helper;
import View.Transaksi.AddOrEditTransaksi;
import java.awt.Color;
import java.awt.Component;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author andid
 */
public class SearchProduk extends javax.swing.JFrame {

    private final ProductController controller = new ProductController();
    private final AddOrEditTransaksi parent;

    /**
     * Creates new form SearchProduk
     */
    public SearchProduk(AddOrEditTransaksi parent) {
        this.parent = parent;

        // never touch initComponents() — it’s regenerated by the GUI builder
        initComponents();

        // now do all your custom wiring:
        configureTable();

        // and finally load the data:
        loadProdukToTable(controller.getAllProduk());
    }

    private void configureTable() {
        // allow multi-row selection
        tabel_data.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        // white background, fill viewport
        tabel_data.setFillsViewportHeight(true);
        tabel_data.setBackground(Color.WHITE);
        jScrollPane1.getViewport().setBackground(Color.WHITE);

        // auto-resize columns
        resizeColumnWidth(tabel_data);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_data = new jtablecustomv2.JTableCustomV2();
        tf_pencarian = new jtextfieldrounded.JTextFieldRounded();
        btn_cari = new jbuttoncustom.JButtonCustom();
        btn_tambah_data = new jbuttoncustom.JButtonCustom();
        btn_batal = new jbuttoncustom.JButtonCustom();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tabel_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel_data);

        tf_pencarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_pencarianActionPerformed(evt);
            }
        });

        btn_cari.setText("CARI PRODUK");
        btn_cari.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });

        btn_tambah_data.setText("TAMBAHKAN DATA");
        btn_tambah_data.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_tambah_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambah_dataActionPerformed(evt);
            }
        });

        btn_batal.setText("BATAL");
        btn_batal.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(tf_pencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btn_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 65, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btn_tambah_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1))))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_pencarian, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(btn_cari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambah_data, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_pencarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_pencarianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_pencarianActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        dispose();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        String kw = tf_pencarian.getText().trim();
        loadProdukToTable(controller.searchProduk(kw));
    }//GEN-LAST:event_btn_cariActionPerformed

    private void btn_tambah_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambah_dataActionPerformed
        int[] rows = tabel_data.getSelectedRows();
        if (rows.length == 0) {
            JOptionPane.showMessageDialog(this, "Pilih setidaknya satu produk!");
            return;
        }
        DefaultTableModel m = (DefaultTableModel) tabel_data.getModel();
        for (int r : rows) {
            String kode = m.getValueAt(r, 0).toString();
            String nama = m.getValueAt(r, 1).toString();
            double harga = Double.parseDouble(m.getValueAt(r, 2).toString());
            // qty=1, no discounts
            parent.addOrMergeProdukItem(new Model.DetailTransaksi(
                    kode, nama, 1, harga, 0.0, 0.0, 0.0, harga
            ));
        }
        parent.updateTotal();
        dispose();
    }//GEN-LAST:event_btn_tambah_dataActionPerformed

    private void loadProdukToTable(List<Produk> list) {
        String[] cols = {"Kode Produk", "Nama Produk", "Harga"};
        DefaultTableModel m = new DefaultTableModel(cols, 0);
        for (Produk p : list) {
            m.addRow(new Object[]{p.getKode(), p.getNama(), p.getHarga()});
        }
        tabel_data.setModel(m);
        resizeColumnWidth(tabel_data);
    }

    private void resizeColumnWidth(JTable table) {
        final TableColumnModel columnModel = table.getColumnModel();
        for (int col = 0; col < table.getColumnCount(); col++) {
            int maxWidth = 50;
            for (int row = 0; row < table.getRowCount(); row++) {
                TableCellRenderer renderer = table.getCellRenderer(row, col);
                Component comp = renderer.getTableCellRendererComponent(
                        table,
                        table.getValueAt(row, col),
                        false, false, row, col);
                maxWidth = Math.max(maxWidth, comp.getPreferredSize().width);
            }
            columnModel.getColumn(col).setPreferredWidth(maxWidth + 10);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchProduk(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private jbuttoncustom.JButtonCustom btn_batal;
    private jbuttoncustom.JButtonCustom btn_cari;
    private jbuttoncustom.JButtonCustom btn_tambah_data;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private jtablecustomv2.JTableCustomV2 tabel_data;
    private jtextfieldrounded.JTextFieldRounded tf_pencarian;
    // End of variables declaration//GEN-END:variables
}
