/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Customer;

import Controller.CustomerController;
import Model.Customer;
import Model.Produk;
import java.awt.Color;
import java.awt.Component;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author andid
 */
public class MenuCustomer extends javax.swing.JPanel {
    
    private CustomerController controller;

    /**
     * Creates new form MenuCustomer
     */
    public MenuCustomer() {
        initComponents();
        
        controller = new CustomerController();
        loadCustomersToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_customer = new jtablecustomv2.JTableCustomV2();
        btn_tambah_customer = new rojerusan.RSMaterialButtonRectangle();
        btn_delete = new rojerusan.RSMaterialButtonRectangle();
        btn_edit = new rojerusan.RSMaterialButtonRectangle();
        tf_pencarian = new jtextfieldrounded.JTextFieldRounded();
        btn_cari = new jbuttoncustom.JButtonCustom();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tabel_customer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_customer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_customerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_customer);

        btn_tambah_customer.setText("Tambah Customer");
        btn_tambah_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambah_customerActionPerformed(evt);
            }
        });

        btn_delete.setBackground(new java.awt.Color(255, 0, 51));
        btn_delete.setText("delete");
        btn_delete.setEnabled(false);
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_edit.setText("edit");
        btn_edit.setEnabled(false);
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        tf_pencarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_pencarianActionPerformed(evt);
            }
        });

        btn_cari.setText("CARI CUSTOMER");
        btn_cari.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_tambah_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1002, Short.MAX_VALUE))
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tf_pencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_pencarian, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambah_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambah_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambah_customerActionPerformed
        new AddOrEditCustomer().setVisible(true);
        
        java.awt.Window win = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (win != null) {
            win.dispose();
        }
    }//GEN-LAST:event_btn_tambah_customerActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        deleteSelectedCustomer();
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        editSelectedCustomer();
    }//GEN-LAST:event_btn_editActionPerformed

    private void tabel_customerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_customerMouseClicked
        btn_delete.setEnabled(true);
        btn_edit.setEnabled(true);
    }//GEN-LAST:event_tabel_customerMouseClicked

    private void tf_pencarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_pencarianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_pencarianActionPerformed

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        String kw = tf_pencarian.getText();
        List<Customer> results = controller.searchCustomers(kw);
        loadCustomersToTable(results);
    }//GEN-LAST:event_btn_cariActionPerformed

    private void loadCustomersToTable() {
        List<Customer> list = controller.getAllCustomers();
        String[] columnNames = {"Kode Cutomer", "Nama", "Alamat"};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);

        for (Customer c : list) {
            String alamat = formatAddress(c);
            Object[] rowData = {
                c.getKodeBaru(),
                c.getNama(),
                alamat
            };
            model.addRow(rowData);
        }

        tabel_customer.setModel(model);
        
        // 1) agar area kosong di bawah baris jadi putih:
        tabel_customer.setFillsViewportHeight(true);
        tabel_customer.setBackground(Color.WHITE);
    
         // 2) dan viewport scrollpane-nya juga putih:
        jScrollPane1.getViewport().setBackground(Color.WHITE);
        
        resizeColumnWidth(tabel_customer);
        
        btn_edit.setEnabled(false);
        btn_delete.setEnabled(false);
    }
    
    private void loadCustomersToTable(List<Customer> list) {
        String[] columnNames = {"Kode Customer","Nama","Alamat"};
        DefaultTableModel model = new DefaultTableModel(columnNames,0);
        for (Customer c : list) {
            model.addRow(new Object[]{
              c.getKodeBaru(),
              c.getNama(),
              formatAddress(c)
            });
        }
        tabel_customer.setModel(model);
        tabel_customer.setFillsViewportHeight(true);
        tabel_customer.setBackground(Color.WHITE);
        jScrollPane1.getViewport().setBackground(Color.WHITE);
        resizeColumnWidth(tabel_customer);
        
        btn_edit.setEnabled(false);
        btn_delete.setEnabled(false);
    }
    
    /**
     * Hapus Customer yang terpilih.
     */
    private void deleteSelectedCustomer() {
        int row = tabel_customer.getSelectedRow();
        if (row < 0) return;
        String kode = tabel_customer.getValueAt(row, 0).toString();
        int confirm = JOptionPane.showConfirmDialog(this,
            String.format("Yakin ingin menghapus customer '%s'?", kode),
            "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            if (controller.deleteCustomer(kode)) {
                JOptionPane.showMessageDialog(this,
                    String.format("Hapus customer %s berhasil.", kode));
                loadCustomersToTable();
            } else {
                JOptionPane.showMessageDialog(this,
                    "Gagal menghapus customer.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    /**
     * Edit Customer yang terpilih.
     */
    private void editSelectedCustomer() {
        int row = tabel_customer.getSelectedRow();
        if (row < 0) return;
        String kode = tabel_customer.getValueAt(row, 0).toString();
        AddOrEditCustomer frame = new AddOrEditCustomer(kode);
        frame.setVisible(true);
        java.awt.Window w = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (w != null) w.dispose();
    }

    /**
     * Format alamat menjadi satu string rapi.
     */
    private String formatAddress(Customer c) {
        return String.format(
            "%s, Des. %s, Kec. %s, Kota %s, %s %s",
            c.getAlamatLengkap(),
            c.getKelurahan(),
            c.getKecamatan(),
            c.getKota(),
            c.getProvinsi(),
            c.getKodePos()
        );
    }
    
    private void resizeColumnWidth(JTable table) {
    final TableColumnModel columnModel = table.getColumnModel();
    for (int col = 0; col < table.getColumnCount(); col++) {
        int maxWidth = 50; // minimal lebar
        for (int row = 0; row < table.getRowCount(); row++) {
            TableCellRenderer renderer = table.getCellRenderer(row, col);
            Component comp = renderer.getTableCellRendererComponent(
                table,
                table.getValueAt(row, col),
                false, false, row, col
            );
            maxWidth = Math.max(maxWidth, comp.getPreferredSize().width);
        }
        // tambahkan padding kecil supaya teks tidak terlalu mepet
        columnModel.getColumn(col).setPreferredWidth(maxWidth + 10);
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private jbuttoncustom.JButtonCustom btn_cari;
    private rojerusan.RSMaterialButtonRectangle btn_delete;
    private rojerusan.RSMaterialButtonRectangle btn_edit;
    private rojerusan.RSMaterialButtonRectangle btn_tambah_customer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private jtablecustomv2.JTableCustomV2 tabel_customer;
    private jtextfieldrounded.JTextFieldRounded tf_pencarian;
    // End of variables declaration//GEN-END:variables
}
