/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Product;

import Controller.ProductController;
import Util.Helper;
import Model.Produk;
import Util.OperationResult;
import java.awt.Component;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author andid
 */
public class MenuProduct extends javax.swing.JPanel {

    private ProductController controller;

    /**
     * Creates new form MenuProduct
     */
    public MenuProduct() {
        initComponents();

        controller = new ProductController();
        loadProdukToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelDasar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_produk = new jtablecustomv2.JTableCustomV2();
        btn_tambah_produk = new rojerusan.RSMaterialButtonRectangle();
        btn_delete = new rojerusan.RSMaterialButtonRectangle();
        btn_edit = new rojerusan.RSMaterialButtonRectangle();
        tf_pencarian = new jtextfieldrounded.JTextFieldRounded();
        btn_cari = new jbuttoncustom.JButtonCustom();

        setLayout(new java.awt.CardLayout());

        PanelDasar.setBackground(new java.awt.Color(255, 255, 255));

        table_produk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_produk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_produkMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_produk);

        btn_tambah_produk.setText("Tambah Produk");
        btn_tambah_produk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambah_produkActionPerformed(evt);
            }
        });

        btn_delete.setBackground(new java.awt.Color(255, 0, 51));
        btn_delete.setText("delete");
        btn_delete.setEnabled(false);
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_edit.setText("edit");
        btn_edit.setEnabled(false);
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        tf_pencarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_pencarianActionPerformed(evt);
            }
        });

        btn_cari.setText("CARI PRODUK");
        btn_cari.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDasarLayout = new javax.swing.GroupLayout(PanelDasar);
        PanelDasar.setLayout(PanelDasarLayout);
        PanelDasarLayout.setHorizontalGroup(
            PanelDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDasarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PanelDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelDasarLayout.createSequentialGroup()
                        .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_tambah_produk, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1002, Short.MAX_VALUE))
                .addGap(20, 20, 20))
            .addGroup(PanelDasarLayout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(tf_pencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btn_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelDasarLayout.setVerticalGroup(
            PanelDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDasarLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(PanelDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_pencarian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(PanelDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambah_produk, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        add(PanelDasar, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void loadProdukToTable() {
        List<Produk> list = controller.getAllProduk();
        // Define columns
        String[] columnNames = {"Kode", "Nama", "Harga", "Stok"};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);

        // Populate rows
        for (Produk p : list) {
            Object[] rowData = {
                p.getKode(),
                p.getNama(),
                Helper.formatRupiah(p.getHarga()),
                p.getStok()
            };
            model.addRow(rowData);
        }

        // Apply model to the custom table
        table_produk.setModel(model);
        // Reset tombol
        btn_edit.setEnabled(false);
        btn_delete.setEnabled(false);
    }

    /**
     * Hapus produk terpilih.
     */
    private void deleteSelectedProduk() {
        int row = table_produk.getSelectedRow();
        if (row < 0) {
            return;
        }
        String kode = table_produk.getValueAt(row, 0).toString();
        OperationResult res = controller.deleteProduk(kode);
        if (res.isSuccess()) {
            loadProdukToTable();
        } else {
            JOptionPane.showMessageDialog(this, res.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Edit produk terpilih (buka form dengan data terisi).
     */
    private void editSelectedProduk() {
        int row = table_produk.getSelectedRow();
        if (row < 0) {
            return;
        }
        String kode = table_produk.getValueAt(row, 0).toString();
        AddOrEditProduct frame = new AddOrEditProduct(kode);
        frame.setVisible(true);
        // tutup parent window jika perlu
        java.awt.Window win = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (win != null) {
            win.dispose();
        }
    }

    private void resizeColumnWidth(JTable table) {
        final TableColumnModel columnModel = table.getColumnModel();
        for (int col = 0; col < table.getColumnCount(); col++) {
            int maxWidth = 50;
            for (int row = 0; row < table.getRowCount(); row++) {
                TableCellRenderer renderer = table.getCellRenderer(row, col);
                Component comp = renderer.getTableCellRendererComponent(
                        table,
                        table.getValueAt(row, col),
                        false, false, row, col);
                maxWidth = Math.max(maxWidth, comp.getPreferredSize().width);
            }
            columnModel.getColumn(col).setPreferredWidth(maxWidth + 10);
        }
    }

    private void btn_tambah_produkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambah_produkActionPerformed
        AddOrEditProduct frame = new AddOrEditProduct();
        frame.setVisible(true);
        frame.revalidate();

        // 1) Cari window/top‐level ancestor (biasanya MainFrame)
        java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (window != null) {
            window.dispose();   // ini akan menutup frame induk
        }
    }//GEN-LAST:event_btn_tambah_produkActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        deleteSelectedProduk();
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        editSelectedProduk();
    }//GEN-LAST:event_btn_editActionPerformed

    private void table_produkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_produkMouseClicked
        btn_edit.setEnabled(true);
        btn_delete.setEnabled(true);
    }//GEN-LAST:event_table_produkMouseClicked

    private void tf_pencarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_pencarianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_pencarianActionPerformed

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        String kw = tf_pencarian.getText().trim();
        loadProdukToTable(controller.searchProduk(kw));
    }//GEN-LAST:event_btn_cariActionPerformed

    private void loadProdukToTable(List<Produk> list) {
        String[] cols = {"Kode Produk", "Nama Produk", "Harga"};
        DefaultTableModel m = new DefaultTableModel(cols, 0);
        for (Produk p : list) {
            m.addRow(new Object[]{p.getKode(), p.getNama(), p.getHarga()});
        }
        table_produk.setModel(m);
        resizeColumnWidth(table_produk);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelDasar;
    private jbuttoncustom.JButtonCustom btn_cari;
    private rojerusan.RSMaterialButtonRectangle btn_delete;
    private rojerusan.RSMaterialButtonRectangle btn_edit;
    private rojerusan.RSMaterialButtonRectangle btn_tambah_produk;
    private javax.swing.JScrollPane jScrollPane1;
    private jtablecustomv2.JTableCustomV2 table_produk;
    private jtextfieldrounded.JTextFieldRounded tf_pencarian;
    // End of variables declaration//GEN-END:variables
}
