/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import View.Customer.MenuCustomer;
import View.Product.MenuProduct;
import View.Transaksi.MenuTransaksi;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author andid
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {        
        this(1);
    }
    
    public MenuUtama(int menuIndex) {
        initComponents();
        switch (menuIndex) {
            case 2:
                setMenuAktif(pn_btn_customer, pn_lbl_actv_customer);
                pn_utama.add(new MenuCustomer());
                break;
            case 3:
                setMenuAktif(pn_btn_transaksi, pn_lbl_actv_transaksi);
                pn_utama.add(new MenuTransaksi());
                break;
            case 1:
            default:
                setMenuAktif(pn_btn_produk, pn_lbl_actv_produk);
                pn_utama.add(new MenuProduct());
                break;
        }
        pn_utama.repaint();
        pn_utama.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_kiri = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pn_btn_produk = new javax.swing.JPanel();
        pn_lbl_actv_produk = new javax.swing.JPanel();
        btn_produk = new javax.swing.JLabel();
        pn_btn_customer = new javax.swing.JPanel();
        pn_lbl_actv_customer = new javax.swing.JPanel();
        btn_customer = new javax.swing.JLabel();
        pn_btn_transaksi = new javax.swing.JPanel();
        pn_lbl_actv_transaksi = new javax.swing.JPanel();
        btn_transaksi = new javax.swing.JLabel();
        pn_kanan = new javax.swing.JPanel();
        jPanelGradient1 = new jpanelgradient.JPanelGradient();
        pn_dasar = new javax.swing.JPanel();
        pn_utama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setSize(new java.awt.Dimension(1366, 768));

        pn_kiri.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("Mayusa Shop");

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Menu Utama");

        pn_btn_produk.setBackground(new java.awt.Color(255, 255, 255));
        pn_btn_produk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_btn_produkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_btn_produkMouseExited(evt);
            }
        });

        pn_lbl_actv_produk.setBackground(new java.awt.Color(255, 255, 255));

        org.jdesktop.layout.GroupLayout pn_lbl_actv_produkLayout = new org.jdesktop.layout.GroupLayout(pn_lbl_actv_produk);
        pn_lbl_actv_produk.setLayout(pn_lbl_actv_produkLayout);
        pn_lbl_actv_produkLayout.setHorizontalGroup(
            pn_lbl_actv_produkLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 5, Short.MAX_VALUE)
        );
        pn_lbl_actv_produkLayout.setVerticalGroup(
            pn_lbl_actv_produkLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 0, Short.MAX_VALUE)
        );

        btn_produk.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btn_produk.setForeground(new java.awt.Color(102, 102, 102));
        btn_produk.setText("Produk");
        btn_produk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_produkMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_produkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_produkMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_produkMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_produkMouseReleased(evt);
            }
        });

        org.jdesktop.layout.GroupLayout pn_btn_produkLayout = new org.jdesktop.layout.GroupLayout(pn_btn_produk);
        pn_btn_produk.setLayout(pn_btn_produkLayout);
        pn_btn_produkLayout.setHorizontalGroup(
            pn_btn_produkLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pn_btn_produkLayout.createSequentialGroup()
                .add(pn_lbl_actv_produk, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(btn_produk, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_btn_produkLayout.setVerticalGroup(
            pn_btn_produkLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pn_lbl_actv_produk, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(btn_produk, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        pn_btn_customer.setBackground(new java.awt.Color(255, 255, 255));
        pn_btn_customer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_btn_customerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_btn_customerMouseExited(evt);
            }
        });

        pn_lbl_actv_customer.setBackground(new java.awt.Color(255, 255, 255));

        org.jdesktop.layout.GroupLayout pn_lbl_actv_customerLayout = new org.jdesktop.layout.GroupLayout(pn_lbl_actv_customer);
        pn_lbl_actv_customer.setLayout(pn_lbl_actv_customerLayout);
        pn_lbl_actv_customerLayout.setHorizontalGroup(
            pn_lbl_actv_customerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 5, Short.MAX_VALUE)
        );
        pn_lbl_actv_customerLayout.setVerticalGroup(
            pn_lbl_actv_customerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 0, Short.MAX_VALUE)
        );

        btn_customer.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btn_customer.setForeground(new java.awt.Color(102, 102, 102));
        btn_customer.setText("Customer");
        btn_customer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_customerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_customerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_customerMouseExited(evt);
            }
        });

        org.jdesktop.layout.GroupLayout pn_btn_customerLayout = new org.jdesktop.layout.GroupLayout(pn_btn_customer);
        pn_btn_customer.setLayout(pn_btn_customerLayout);
        pn_btn_customerLayout.setHorizontalGroup(
            pn_btn_customerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pn_btn_customerLayout.createSequentialGroup()
                .add(pn_lbl_actv_customer, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(btn_customer, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_btn_customerLayout.setVerticalGroup(
            pn_btn_customerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pn_lbl_actv_customer, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(btn_customer, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        pn_btn_transaksi.setBackground(new java.awt.Color(255, 255, 255));
        pn_btn_transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_btn_transaksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_btn_transaksiMouseExited(evt);
            }
        });

        pn_lbl_actv_transaksi.setBackground(new java.awt.Color(255, 255, 255));

        org.jdesktop.layout.GroupLayout pn_lbl_actv_transaksiLayout = new org.jdesktop.layout.GroupLayout(pn_lbl_actv_transaksi);
        pn_lbl_actv_transaksi.setLayout(pn_lbl_actv_transaksiLayout);
        pn_lbl_actv_transaksiLayout.setHorizontalGroup(
            pn_lbl_actv_transaksiLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 5, Short.MAX_VALUE)
        );
        pn_lbl_actv_transaksiLayout.setVerticalGroup(
            pn_lbl_actv_transaksiLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 0, Short.MAX_VALUE)
        );

        btn_transaksi.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btn_transaksi.setForeground(new java.awt.Color(102, 102, 102));
        btn_transaksi.setText("Transaksi");
        btn_transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_transaksiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_transaksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_transaksiMouseExited(evt);
            }
        });

        org.jdesktop.layout.GroupLayout pn_btn_transaksiLayout = new org.jdesktop.layout.GroupLayout(pn_btn_transaksi);
        pn_btn_transaksi.setLayout(pn_btn_transaksiLayout);
        pn_btn_transaksiLayout.setHorizontalGroup(
            pn_btn_transaksiLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pn_btn_transaksiLayout.createSequentialGroup()
                .add(pn_lbl_actv_transaksi, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(btn_transaksi, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_btn_transaksiLayout.setVerticalGroup(
            pn_btn_transaksiLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pn_lbl_actv_transaksi, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(btn_transaksi, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout pn_kiriLayout = new org.jdesktop.layout.GroupLayout(pn_kiri);
        pn_kiri.setLayout(pn_kiriLayout);
        pn_kiriLayout.setHorizontalGroup(
            pn_kiriLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, pn_kiriLayout.createSequentialGroup()
                .add(20, 20, 20)
                .add(pn_kiriLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(pn_btn_produk, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .add(pn_btn_customer, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, pn_btn_transaksi, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(20, 20, 20))
        );
        pn_kiriLayout.setVerticalGroup(
            pn_kiriLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pn_kiriLayout.createSequentialGroup()
                .add(21, 21, 21)
                .add(jLabel1)
                .add(30, 30, 30)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pn_btn_produk, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pn_btn_customer, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pn_btn_transaksi, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(514, Short.MAX_VALUE))
        );

        getContentPane().add(pn_kiri, java.awt.BorderLayout.LINE_START);

        pn_kanan.setBackground(new java.awt.Color(255, 255, 255));
        pn_kanan.setLayout(new java.awt.BorderLayout());

        jPanelGradient1.setColorEnd(new java.awt.Color(0, 255, 204));
        jPanelGradient1.setColorStart(new java.awt.Color(0, 102, 153));

        org.jdesktop.layout.GroupLayout jPanelGradient1Layout = new org.jdesktop.layout.GroupLayout(jPanelGradient1);
        jPanelGradient1.setLayout(jPanelGradient1Layout);
        jPanelGradient1Layout.setHorizontalGroup(
            jPanelGradient1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 1082, Short.MAX_VALUE)
        );
        jPanelGradient1Layout.setVerticalGroup(
            jPanelGradient1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 70, Short.MAX_VALUE)
        );

        pn_kanan.add(jPanelGradient1, java.awt.BorderLayout.PAGE_START);

        pn_dasar.setBackground(new java.awt.Color(250, 250, 250));

        pn_utama.setBackground(new java.awt.Color(255, 255, 255));
        pn_utama.setLayout(new java.awt.BorderLayout());

        org.jdesktop.layout.GroupLayout pn_dasarLayout = new org.jdesktop.layout.GroupLayout(pn_dasar);
        pn_dasar.setLayout(pn_dasarLayout);
        pn_dasarLayout.setHorizontalGroup(
            pn_dasarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pn_dasarLayout.createSequentialGroup()
                .add(20, 20, 20)
                .add(pn_utama, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(20, 20, 20))
        );
        pn_dasarLayout.setVerticalGroup(
            pn_dasarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pn_dasarLayout.createSequentialGroup()
                .add(20, 20, 20)
                .add(pn_utama, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(20, 20, 20))
        );

        pn_kanan.add(pn_dasar, java.awt.BorderLayout.CENTER);

        getContentPane().add(pn_kanan, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private JPanel panelAktif = null;
    private JPanel labelAktif = null;
    
    private void setMenuAktif(JPanel panel, JPanel label) {
        // reset panel+label lama
        if (panelAktif != null) {
            panelAktif.setBackground(Color.WHITE);
            labelAktif.setBackground(Color.WHITE);
        }
        // set panel+label baru
        panel.setBackground(new Color(240,240,240));
        label.setBackground(new Color(0,102,102));
        panelAktif = panel;
        labelAktif = label;
    }
    
    /*
    * Btn Produk - mouse hover/exit event
    */
    
    private void btn_produkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_produkMouseEntered
        pn_btn_produk.setBackground(new Color(250, 250, 250));
        pn_lbl_actv_produk.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_btn_produkMouseEntered

    private void pn_btn_produkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btn_produkMouseExited
        if (panelAktif == pn_btn_produk) {
            // kembalikan ke warna “selected”
            pn_btn_produk.setBackground(new Color(240,240,240));
            pn_lbl_actv_produk.setBackground(new Color(0,102,102));
        } else {
            // default kalau bukan panelAktif
            pn_btn_produk.setBackground(Color.WHITE);
            pn_lbl_actv_produk.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_pn_btn_produkMouseExited

    private void pn_btn_produkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btn_produkMouseEntered
        pn_btn_produk.setBackground(new Color(250, 250, 250));
        pn_lbl_actv_produk.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_pn_btn_produkMouseEntered

    private void btn_produkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_produkMouseExited
        if (panelAktif == pn_btn_produk) {
            // kembalikan ke warna “selected”
            pn_btn_produk.setBackground(new Color(240,240,240));
            pn_lbl_actv_produk.setBackground(new Color(0,102,102));
        } else {
           // default kalau bukan panelAktif
           pn_btn_produk.setBackground(Color.WHITE);
           pn_lbl_actv_produk.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_btn_produkMouseExited

    /*
    * Btn Customer - mouse hover/exit event
    */    
    
    private void btn_customerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_customerMouseEntered
        pn_btn_customer.setBackground(new Color(250, 250, 250));
        pn_lbl_actv_customer.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_btn_customerMouseEntered

    private void btn_customerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_customerMouseExited
        if (panelAktif == pn_btn_customer) {
            pn_btn_customer.setBackground(new Color(240, 240, 240));
            pn_lbl_actv_customer.setBackground(new Color(0, 102, 102));
        } else {
            pn_btn_customer.setBackground(Color.WHITE);
            pn_lbl_actv_customer.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_btn_customerMouseExited

    private void pn_btn_customerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btn_customerMouseEntered
        pn_btn_customer.setBackground(new Color(250, 250, 250));
        pn_lbl_actv_customer.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_pn_btn_customerMouseEntered

    private void pn_btn_customerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btn_customerMouseExited
        if (panelAktif == pn_btn_customer) {
            pn_btn_customer.setBackground(new Color(240, 240, 240));
            pn_lbl_actv_customer.setBackground(new Color(0, 102, 102));
        } else {
            pn_btn_customer.setBackground(Color.WHITE);
            pn_lbl_actv_customer.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_pn_btn_customerMouseExited

    /*
    * Btn Transaksi - mouse hover/exit event
    */
    
    private void btn_transaksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_transaksiMouseEntered
        pn_btn_transaksi.setBackground(new Color(250, 250, 250));
        pn_lbl_actv_transaksi.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_btn_transaksiMouseEntered

    private void btn_transaksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_transaksiMouseExited
        if (panelAktif == pn_btn_transaksi) {
            pn_btn_transaksi.setBackground(new Color(240, 240, 240));
            pn_lbl_actv_transaksi.setBackground(new Color(0, 102, 102));
        } else {
            pn_btn_transaksi.setBackground(Color.WHITE);
            pn_lbl_actv_transaksi.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_btn_transaksiMouseExited

    private void pn_btn_transaksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btn_transaksiMouseEntered
        pn_btn_transaksi.setBackground(new Color(250, 250, 250));
        pn_lbl_actv_transaksi.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_pn_btn_transaksiMouseEntered

    private void pn_btn_transaksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btn_transaksiMouseExited
        if (panelAktif == pn_btn_transaksi) {
            pn_btn_transaksi.setBackground(new Color(240, 240, 240));
            pn_lbl_actv_transaksi.setBackground(new Color(0, 102, 102));
        } else {
            pn_btn_transaksi.setBackground(Color.WHITE);
            pn_lbl_actv_transaksi.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_pn_btn_transaksiMouseExited

    /*
    * Btn Clicked
    */
    
    private void btn_produkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_produkMouseClicked
        setMenuAktif(pn_btn_produk, pn_lbl_actv_produk);
        
        pn_utama.removeAll();
        pn_utama.add(new MenuProduct());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_produkMouseClicked

    private void btn_produkMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_produkMousePressed
        
    }//GEN-LAST:event_btn_produkMousePressed

    private void btn_produkMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_produkMouseReleased
        
    }//GEN-LAST:event_btn_produkMouseReleased

    private void btn_customerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_customerMouseClicked
        setMenuAktif(pn_btn_customer, pn_lbl_actv_customer);
        
        pn_utama.removeAll();
        pn_utama.add(new MenuCustomer());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_customerMouseClicked

    private void btn_transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_transaksiMouseClicked
        setMenuAktif(pn_btn_transaksi, pn_lbl_actv_transaksi);
        
        pn_utama.removeAll();
        pn_utama.add(new MenuTransaksi());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_transaksiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_customer;
    private javax.swing.JLabel btn_produk;
    private javax.swing.JLabel btn_transaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private jpanelgradient.JPanelGradient jPanelGradient1;
    private javax.swing.JPanel pn_btn_customer;
    private javax.swing.JPanel pn_btn_produk;
    private javax.swing.JPanel pn_btn_transaksi;
    private javax.swing.JPanel pn_dasar;
    private javax.swing.JPanel pn_kanan;
    private javax.swing.JPanel pn_kiri;
    private javax.swing.JPanel pn_lbl_actv_customer;
    private javax.swing.JPanel pn_lbl_actv_produk;
    private javax.swing.JPanel pn_lbl_actv_transaksi;
    private javax.swing.JPanel pn_utama;
    // End of variables declaration//GEN-END:variables
}
