/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Transaksi;

import Controller.TransactionController;
import Main.MenuUtama;
import Model.DetailTransaksi;
import Model.FullTransaksi;
import Util.Helper;
import View.Search.SearchCustomer;
import View.Search.SearchProduk;
import View.Transaksi.ProdukItem.ProdukItem;
import java.awt.Component;
import java.sql.Date;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

/**
 *
 * @author andid
 */
public class AddOrEditTransaksi extends javax.swing.JFrame {

    private final TransactionController controller;
    private final boolean isEdit;
    private final List<ProdukItem> produkItems = new ArrayList<>();

    /**
     * Creates new form AddOrEditTransaksi
     */
    public AddOrEditTransaksi() {

        controller = new TransactionController();
        isEdit = false;

        initComponents();

        pn_utama_produk_item.setLayout(
                new javax.swing.BoxLayout(pn_utama_produk_item,
                        javax.swing.BoxLayout.Y_AXIS)
        );

        // 2) Auto-generate invoice no. dan tanggal hari ini
        String noInvBaru = controller.generateInvoiceNo();
        tf_no_invoice.setText(noInvBaru);
        tf_no_invoice.setEditable(false);

        // pakai Helper.formatDate untuk format "dd-MM-yyyy"
        java.sql.Date sekarang = new java.sql.Date(System.currentTimeMillis());
        tf_tanggal_invoice.setText(Helper.formatDate(sekarang));
    }

    public AddOrEditTransaksi(String noInv) {
        controller = new TransactionController();
        isEdit = true;
        initComponents();

        // setup panel vertikal
        pn_utama_produk_item.setLayout(
                new javax.swing.BoxLayout(pn_utama_produk_item,
                        javax.swing.BoxLayout.Y_AXIS)
        );

        // muat header + detail dari DB
        FullTransaksi ft = controller.getFullTransaksi(noInv);
        if (ft == null) {
            JOptionPane.showMessageDialog(this,
                    "Invoice " + noInv + " tidak ditemukan.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            dispose();
            return;
        }

        // isi header
        tf_no_invoice.setText(ft.getNoInv());
        tf_no_invoice.setEditable(false);
        tf_tanggal_invoice.setText(Helper.formatDate(ft.getTglInv()));
        tf_kode_customer.setText(ft.getKodeCust());
        tf_nama_customer.setText(ft.getNamaCust());
        tf_total_harga.setText(Helper.formatRupiah(ft.getTotal()));

        // muat tiap detail
        for (DetailTransaksi d : ft.getDetailList()) {
            addProdukItem(d);
        }

        updateTotal();
    }

    /**
     * Tambah beberapa dummy DetailTransaksi agar ProdukItem tampil di UI
     */
    private void addDummyData() {
        // Contoh dummy data
        DetailTransaksi d1 = new DetailTransaksi("P001", "Produk A", 2,
                2 * 50000.0, 0.0, 0.0, 0.0, 50000.0);
        DetailTransaksi d2 = new DetailTransaksi("P002", "Produk B", 1,
                1 * 75000.0, 5.0, 0.0, 0.0, 71250.0);
        DetailTransaksi d3 = new DetailTransaksi("P003", "Produk C", 3,
                3 * 30000.0, 0.0, 10.0, 5.0, 81000.0);

        addProdukItem(d1);
        addProdukItem(d2);
        addProdukItem(d3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tf_no_invoice = new jtextfieldrounded.JTextFieldRounded();
        jLabel5 = new javax.swing.JLabel();
        tf_tanggal_invoice = new jtextfieldrounded.JTextFieldRounded();
        jLabel6 = new javax.swing.JLabel();
        tf_total_harga = new jtextfieldrounded.JTextFieldRounded();
        btn_refresh_total_harga = new jbuttoncustom.JButtonCustom();
        jPanel6 = new javax.swing.JPanel();
        tf_kode_customer = new jtextfieldrounded.JTextFieldRounded();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_nama_customer = new jtextfieldrounded.JTextFieldRounded();
        btn_cari_customer = new jbuttoncustom.JButtonCustom();
        pn_produk_list = new javax.swing.JScrollPane();
        pn_utama_produk_item = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btn_back = new jbuttoncustom.JButtonCustom();
        btn_simpan = new jbuttoncustom.JButtonCustom();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn_tambah_produk = new jbuttoncustom.JButtonCustom();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setText("TRANSAKSI");
        jPanel2.add(jLabel1);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setText("Nomor Invoice");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel5.setText("Tanggal Invoice");

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setText("Total Harga");

        btn_refresh_total_harga.setText("REFRESH TOTAL HARGA");
        btn_refresh_total_harga.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_refresh_total_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refresh_total_hargaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(tf_no_invoice, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(tf_tanggal_invoice, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap())
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(tf_total_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_refresh_total_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_total_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_refresh_total_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_tanggal_invoice, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_no_invoice, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel7.setText("Kode Customer");

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel8.setText("Nama Customer");

        btn_cari_customer.setText("Cari Customer");
        btn_cari_customer.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_cari_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cari_customerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(tf_kode_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(tf_nama_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(btn_cari_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_kode_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nama_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cari_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pn_produk_list.setBackground(new java.awt.Color(255, 255, 255));

        pn_utama_produk_item.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pn_utama_produk_itemLayout = new javax.swing.GroupLayout(pn_utama_produk_item);
        pn_utama_produk_item.setLayout(pn_utama_produk_itemLayout);
        pn_utama_produk_itemLayout.setHorizontalGroup(
            pn_utama_produk_itemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1315, Short.MAX_VALUE)
        );
        pn_utama_produk_itemLayout.setVerticalGroup(
            pn_utama_produk_itemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );

        pn_produk_list.setViewportView(pn_utama_produk_item);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        btn_back.setText("KEMBALI");
        btn_back.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        btn_simpan.setText("SIMPAN");
        btn_simpan.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel2.setText("Customer");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel2))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel2))
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel3.setText("Produk");

        btn_tambah_produk.setText("TAMBAH PRODUK");
        btn_tambah_produk.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_tambah_produk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambah_produkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_tambah_produk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_tambah_produk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_produk_list, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pn_produk_list, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void updateTotal() {
        // kumpulkan detail dari UI
        List<DetailTransaksi> details = new ArrayList<>();
        for (Component comp : pn_utama_produk_item.getComponents()) {
            if (comp instanceof ProdukItem) {
                details.add(((ProdukItem) comp).getDetail());
            }
        }

        // hitung total sebagai sum dari setiap jumlah detail
        double total = 0;
        for (DetailTransaksi d : details) {
            total += d.getJumlah();
        }
        // atau dengan Java 8 streams:
        // double total = details.stream().mapToDouble(DetailTransaksi::getJumlah).sum();

        // tampilkan di UI (opsional, jika Anda ingin memperbarui tf_total_harga)
        tf_total_harga.setText(Helper.formatRupiah(total));
    }

    /**
     * Simpan atau update transaksi ke DB
     */
    private void saveTransaksi() {
        // parsing tanggal
        Date sqlDate;
        try {
            java.util.Date u = new SimpleDateFormat("dd-MM-yyyy")
                    .parse(tf_tanggal_invoice.getText());
            sqlDate = new Date(u.getTime());
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Format tanggal tidak valid.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // kumpulkan detail dari UI
        List<DetailTransaksi> details = new ArrayList<>();
        for (Component comp : pn_utama_produk_item.getComponents()) {
            if (comp instanceof ProdukItem) {
                details.add(((ProdukItem) comp).getDetail());
            }
        }

        // hitung total sebagai sum dari setiap jumlah detail
        double total = 0;
        for (DetailTransaksi d : details) {
            total += d.getJumlah();
        }

        // buat model Transaksi
        Model.Transaksi trx = new Model.Transaksi(
                tf_no_invoice.getText(),
                tf_kode_customer.getText(),
                sqlDate,
                total,
                details
        );

        // eksekusi save/update
        boolean ok = isEdit
                ? controller.updateTransaksi(trx)
                : controller.saveTransaksi(trx);

        if (ok) {
            JOptionPane.showMessageDialog(this,
                    isEdit ? "Transaksi berhasil diupdate."
                            : "Transaksi berhasil disimpan.");
            new Main.MenuUtama(3).setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this,
                    "Gagal menyimpan transaksi.",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        new MenuUtama(3).setVisible(true);

        dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        saveTransaksi();
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_cari_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cari_customerActionPerformed
        new SearchCustomer(this).setVisible(true);
    }//GEN-LAST:event_btn_cari_customerActionPerformed

    private void btn_refresh_total_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refresh_total_hargaActionPerformed
        updateTotal();
    }//GEN-LAST:event_btn_refresh_total_hargaActionPerformed

    private void btn_tambah_produkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambah_produkActionPerformed
        new SearchProduk(this).setVisible(true);
    }//GEN-LAST:event_btn_tambah_produkActionPerformed

    public void addProdukItem(DetailTransaksi d) {
        ProdukItem item = new ProdukItem();
        if (d != null) {
            // kalau edit, isi field dari objek DetailTransaksi
            item.setKodeProduk(d.getKodeProduk());
            item.setNamaProduk(d.getNamaProduk());
            item.setQty(d.getQty());
            item.setDsc1(d.getDsc1());
            item.setDsc2(d.getDsc2());
            item.setDsc3(d.getDsc3());
            item.setHargaProduk(d.getHargaAkhir());
            item.setJumlah(d.getJumlah());
        }
        produkItems.add(item);
        pn_utama_produk_item.add(item);
        // refresh supaya scrollpane tahu konten baru
        pn_utama_produk_item.revalidate();
        pn_utama_produk_item.repaint();
    }

    public void addOrMergeProdukItem(DetailTransaksi d) {
        for (ProdukItem item : produkItems) {
            if (item.getKodeProduk().equals(d.getKodeProduk())) {
                // merge: tambah qty
                int newQty = item.getQty() + d.getQty();
                item.setQty(newQty);

                // trigger recalculation di panel: getDetail() akan
                // hitung ulang jumlah dan set ke tf_jumlah
                item.getDetail();

                // refresh UI
                pn_utama_produk_item.revalidate();
                pn_utama_produk_item.repaint();
                updateTotal();
                return;
            }
        }
        // kalau belum ada, tambah baru
        addProdukItem(d);
        updateTotal();
    }

    public void setCustomer(String kode, String nama) {
        tf_kode_customer.setText(kode);
        tf_nama_customer.setText(nama);
    }

    public void removeProdukItem(ProdukItem item) {
        // 1) Hapus dari list model
        produkItems.remove(item);
        // 2) Hapus dari UI
        pn_utama_produk_item.remove(item);
        // 3) Refresh layout & hitung ulang total
        pn_utama_produk_item.revalidate();
        pn_utama_produk_item.repaint();
        updateTotal();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddOrEditTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddOrEditTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddOrEditTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddOrEditTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddOrEditTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private jbuttoncustom.JButtonCustom btn_back;
    private jbuttoncustom.JButtonCustom btn_cari_customer;
    private jbuttoncustom.JButtonCustom btn_refresh_total_harga;
    private jbuttoncustom.JButtonCustom btn_simpan;
    private jbuttoncustom.JButtonCustom btn_tambah_produk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane pn_produk_list;
    private javax.swing.JPanel pn_utama_produk_item;
    private jtextfieldrounded.JTextFieldRounded tf_kode_customer;
    private jtextfieldrounded.JTextFieldRounded tf_nama_customer;
    private jtextfieldrounded.JTextFieldRounded tf_no_invoice;
    private jtextfieldrounded.JTextFieldRounded tf_tanggal_invoice;
    private jtextfieldrounded.JTextFieldRounded tf_total_harga;
    // End of variables declaration//GEN-END:variables
}
