/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Transaksi;

import Controller.TransactionController;
import Util.Helper;
import Model.FullTransaksi;
import java.awt.Color;
import java.awt.Component;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author andid
 */
public class MenuTransaksi extends javax.swing.JPanel {
    
    private TransactionController controller;

    /**
     * Creates new form MenuTransaksi
     */
    public MenuTransaksi() {
        initComponents();
        
        controller = new TransactionController();
        loadTransaksiToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelDasar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_transaksi = new jtablecustomv2.JTableCustomV2();
        btn_delete = new rojerusan.RSMaterialButtonRectangle();
        btn_tambah_transaksi = new rojerusan.RSMaterialButtonRectangle();
        btn_edit = new rojerusan.RSMaterialButtonRectangle();

        setLayout(new java.awt.CardLayout());

        PanelDasar.setBackground(new java.awt.Color(255, 255, 255));

        tabel_transaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_transaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_transaksi);

        btn_delete.setBackground(new java.awt.Color(255, 0, 51));
        btn_delete.setText("DELETE");
        btn_delete.setEnabled(false);
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_tambah_transaksi.setText("Tambah Transaksi");
        btn_tambah_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambah_transaksiActionPerformed(evt);
            }
        });

        btn_edit.setText("edit");
        btn_edit.setEnabled(false);
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDasarLayout = new javax.swing.GroupLayout(PanelDasar);
        PanelDasar.setLayout(PanelDasarLayout);
        PanelDasarLayout.setHorizontalGroup(
            PanelDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDasarLayout.createSequentialGroup()
                .addGroup(PanelDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelDasarLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_tambah_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelDasarLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1002, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        PanelDasarLayout.setVerticalGroup(
            PanelDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDasarLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(PanelDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_edit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_tambah_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        add(PanelDasar, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void deleteSelectedTransaksi() {
        int row = tabel_transaksi.getSelectedRow();
        if (row < 0) return;
        String noInv = tabel_transaksi.getValueAt(row, 0).toString();
        int confirm = JOptionPane.showConfirmDialog(this,
            String.format("Hapus transaksi %s?", noInv),
            "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            if (controller.deleteTransaksi(noInv)) {
                JOptionPane.showMessageDialog(this,
                    String.format("Transaksi %s berhasil dihapus.", noInv));
                loadTransaksiToTable();
            } else {
                JOptionPane.showMessageDialog(this,
                    "Gagal menghapus transaksi.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void editSelectedTransaksi() {
        int row = tabel_transaksi.getSelectedRow();
        if (row < 0) return;
        String noInv = tabel_transaksi.getValueAt(row, 0).toString();
        AddOrEditTransaksi frame = new AddOrEditTransaksi(noInv);
        frame.setVisible(true);
        java.awt.Window w = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (w != null) w.dispose();
    }
    
    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        deleteSelectedTransaksi();
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_tambah_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambah_transaksiActionPerformed
        AddOrEditTransaksi frame = new AddOrEditTransaksi();
        frame.setVisible(true);
        frame.revalidate();
        
        // 1) Cari window/top‐level ancestor (biasanya MainFrame)
        java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (window != null) {
            window.dispose();   // ini akan menutup frame induk
        }
    }//GEN-LAST:event_btn_tambah_transaksiActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        editSelectedTransaksi();
    }//GEN-LAST:event_btn_editActionPerformed

    private void tabel_transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_transaksiMouseClicked
        btn_delete.setEnabled(true);
        btn_edit.setEnabled(true);
    }//GEN-LAST:event_tabel_transaksiMouseClicked

    
    private void loadTransaksiToTable() {
        List<FullTransaksi> list = controller.getAllFullTransaksi();
        String[] columnNames = {"No Invoice", "Kode Cust", "Nama Cust", "Alamat Cust", "Tgl Inv", "Total"};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);

        for (FullTransaksi ft : list) {
            Object[] row = {
                ft.getNoInv(),
                ft.getKodeCust(),
                ft.getNamaCust(),
                ft.getAlamatCust(),
                Helper.formatDate(ft.getTglInv()),    // format dd-MM-yyyy
                Helper.formatRupiah(ft.getTotal()) 
            };
            model.addRow(row);
        }

        // Set model dan pengaturan tampilan
        tabel_transaksi.setModel(model);
        tabel_transaksi.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tabel_transaksi.setFillsViewportHeight(true);
        tabel_transaksi.setBackground(Color.WHITE);
        jScrollPane1.getViewport().setBackground(Color.WHITE);

        // Resize kolom otomatis
        resizeColumnWidth(tabel_transaksi);
        btn_delete.setEnabled(false);
        btn_edit.setEnabled(false);
    }

    /**
     * Resize tiap kolom agar muat konten terpanjang.
     */
    private void resizeColumnWidth(JTable table) {
        final TableColumnModel columnModel = table.getColumnModel();
        for (int col = 0; col < table.getColumnCount(); col++) {
            int maxWidth = 50;
            for (int row = 0; row < table.getRowCount(); row++) {
                TableCellRenderer renderer = table.getCellRenderer(row, col);
                Component comp = renderer.getTableCellRendererComponent(
                    table,
                    table.getValueAt(row, col),
                    false, false,
                    row, col
                );
                maxWidth = Math.max(maxWidth, comp.getPreferredSize().width);
            }
            columnModel.getColumn(col).setPreferredWidth(maxWidth + 10);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelDasar;
    private rojerusan.RSMaterialButtonRectangle btn_delete;
    private rojerusan.RSMaterialButtonRectangle btn_edit;
    private rojerusan.RSMaterialButtonRectangle btn_tambah_transaksi;
    private javax.swing.JScrollPane jScrollPane1;
    private jtablecustomv2.JTableCustomV2 tabel_transaksi;
    // End of variables declaration//GEN-END:variables
}
