/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Transaksi.ProdukItem;

import Model.DetailTransaksi;
import Util.Helper;
import View.Transaksi.AddOrEditTransaksi;

/**
 *
 * @author andid
 */
public class ProdukItem extends javax.swing.JPanel {

    /**
     * Creates new form ProdukItem
     */
    public ProdukItem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tf_kode_produk = new jtextfieldrounded.JTextFieldRounded();
        jLabel2 = new javax.swing.JLabel();
        tf_qty_produk = new jtextfieldrounded.JTextFieldRounded();
        jLabel3 = new javax.swing.JLabel();
        tf_harga_produk = new jtextfieldrounded.JTextFieldRounded();
        jLabel4 = new javax.swing.JLabel();
        tf_nama_produk = new jtextfieldrounded.JTextFieldRounded();
        jLabel5 = new javax.swing.JLabel();
        tf_dsc1_produk = new jtextfieldrounded.JTextFieldRounded();
        tf_dsc2_produk = new jtextfieldrounded.JTextFieldRounded();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_dsc3_produk = new jtextfieldrounded.JTextFieldRounded();
        jLabel8 = new javax.swing.JLabel();
        tf_jumlah = new jtextfieldrounded.JTextFieldRounded();
        jSeparator1 = new javax.swing.JSeparator();
        btn_hapus_produk = new jbuttoncustom.JButtonCustom();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setText("Kode Produk");

        tf_kode_produk.setText("Masukkan kode produk");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setText("Qty");

        tf_qty_produk.setText("Masukkan qty produk");
        tf_qty_produk.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_qty_produkFocusLost(evt);
            }
        });
        tf_qty_produk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_qty_produkActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setText("Harga Produk");

        tf_harga_produk.setText("Harga produk");
        tf_harga_produk.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_harga_produkFocusLost(evt);
            }
        });
        tf_harga_produk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_harga_produkActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setText("Nama Produk");

        tf_nama_produk.setText("Nama produk");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel5.setText("Discount 1");

        tf_dsc1_produk.setText("Masukkan discount produk");
        tf_dsc1_produk.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_dsc1_produkFocusLost(evt);
            }
        });
        tf_dsc1_produk.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                tf_dsc1_produkInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        tf_dsc1_produk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_dsc1_produkActionPerformed(evt);
            }
        });

        tf_dsc2_produk.setText("Masukkan discount produk");
        tf_dsc2_produk.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_dsc2_produkFocusLost(evt);
            }
        });
        tf_dsc2_produk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_dsc2_produkActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setText("Discount 2");

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel7.setText("Discount 3");

        tf_dsc3_produk.setText("Masukkan discount produk");
        tf_dsc3_produk.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_dsc3_produkFocusLost(evt);
            }
        });
        tf_dsc3_produk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_dsc3_produkActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel8.setText("Jumlah");

        tf_jumlah.setText("Jumlah harga akan muncul disini");
        tf_jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_jumlahActionPerformed(evt);
            }
        });

        btn_hapus_produk.setText("HAPUS PRODUK");
        btn_hapus_produk.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_hapus_produk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapus_produkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(tf_kode_produk, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(tf_qty_produk, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(tf_dsc1_produk, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(tf_nama_produk, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(tf_dsc2_produk, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(tf_dsc3_produk, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(tf_harga_produk, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(390, 390, 390)
                                .addComponent(btn_hapus_produk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel8)
                    .addComponent(tf_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
            .addComponent(jSeparator1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_kode_produk, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_nama_produk, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_harga_produk, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(btn_hapus_produk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_qty_produk, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_dsc1_produk, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_dsc2_produk, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_dsc3_produk, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    public void setKodeProduk(String kode) {
        tf_kode_produk.setText(kode);
    }

    public void setNamaProduk(String nama) {
        tf_nama_produk.setText(nama);
    }

    public void setQty(int qty) {
        tf_qty_produk.setText(String.valueOf(qty));
    }

    public void setDsc1(double d1) {
        tf_dsc1_produk.setText(String.valueOf(d1));
    }

    public void setDsc2(double d2) {
        tf_dsc2_produk.setText(String.valueOf(d2));
    }

    public void setDsc3(double d3) {
        tf_dsc3_produk.setText(String.valueOf(d3));
    }

    public void setHargaProduk(double h) {
        tf_harga_produk.setText(String.valueOf(h));
    }

    public void setJumlah(double j) {
        tf_jumlah.setText(String.valueOf(j));
    }

    private void tf_qty_produkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_qty_produkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_qty_produkActionPerformed

    private void tf_harga_produkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_harga_produkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_harga_produkActionPerformed

    private void tf_dsc1_produkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_dsc1_produkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_dsc1_produkActionPerformed

    private void tf_dsc2_produkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_dsc2_produkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_dsc2_produkActionPerformed

    private void tf_dsc3_produkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_dsc3_produkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_dsc3_produkActionPerformed

    private void tf_jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_jumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_jumlahActionPerformed

    private void tf_dsc1_produkInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tf_dsc1_produkInputMethodTextChanged

    }//GEN-LAST:event_tf_dsc1_produkInputMethodTextChanged

    private void tf_dsc1_produkFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_dsc1_produkFocusLost
        getDetail();
    }//GEN-LAST:event_tf_dsc1_produkFocusLost

    private void tf_dsc2_produkFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_dsc2_produkFocusLost
        getDetail();
    }//GEN-LAST:event_tf_dsc2_produkFocusLost

    private void tf_dsc3_produkFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_dsc3_produkFocusLost
        getDetail();
    }//GEN-LAST:event_tf_dsc3_produkFocusLost

    private void tf_qty_produkFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_qty_produkFocusLost
        getDetail();
    }//GEN-LAST:event_tf_qty_produkFocusLost

    private void tf_harga_produkFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_harga_produkFocusLost
        getDetail();
    }//GEN-LAST:event_tf_harga_produkFocusLost

    private void btn_hapus_produkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapus_produkActionPerformed
        java.awt.Window win = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (win instanceof AddOrEditTransaksi) {
            // Minta induk menghapus panel ini
            ((AddOrEditTransaksi) win).removeProdukItem(this);
        }
    }//GEN-LAST:event_btn_hapus_produkActionPerformed

    // helper method in ProdukItem:
    private void notifyParentToRecalc() {
        java.awt.Window win = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (win instanceof AddOrEditTransaksi) {
            ((AddOrEditTransaksi) win).updateTotal();
        }
    }

    public DetailTransaksi getDetail() {
        String kode = tf_kode_produk.getText();
        String nama = tf_nama_produk.getText();
        double harga = Double.parseDouble(tf_harga_produk.getText());
        int qty = Integer.parseInt(tf_qty_produk.getText());
        double d1 = Double.parseDouble(tf_dsc1_produk.getText());
        double d2 = Double.parseDouble(tf_dsc2_produk.getText());
        double d3 = Double.parseDouble(tf_dsc3_produk.getText());

        // diskon bertingkat
        double afterD1 = harga * (1 - d1 / 100.0);
        double afterD2 = afterD1 * (1 - d2 / 100.0);
        double afterD3 = afterD2 * (1 - d3 / 100.0);

        // total baris = harga akhir (afterD3) × qty
        double jumlah = afterD3 * qty;

        tf_jumlah.setText(Helper.formatRupiah(jumlah));

        return new DetailTransaksi(
                kode,
                nama,
                qty,
                jumlah, // total setelah diskon
                d1,
                d2,
                d3,
                harga // harga produk asli
        );
    }

    /**
     * Kode produk yang sedang ditampilkan di panel ini.
     */
    public String getKodeProduk() {
        return tf_kode_produk.getText();
    }

    /**
     * Qty saat ini (dari tf_qty_produk).
     */
    public int getQty() {
        try {
            return Integer.parseInt(tf_qty_produk.getText());
        } catch (NumberFormatException ex) {
            return 0;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private jbuttoncustom.JButtonCustom btn_hapus_produk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private jtextfieldrounded.JTextFieldRounded tf_dsc1_produk;
    private jtextfieldrounded.JTextFieldRounded tf_dsc2_produk;
    private jtextfieldrounded.JTextFieldRounded tf_dsc3_produk;
    private jtextfieldrounded.JTextFieldRounded tf_harga_produk;
    private jtextfieldrounded.JTextFieldRounded tf_jumlah;
    private jtextfieldrounded.JTextFieldRounded tf_kode_produk;
    private jtextfieldrounded.JTextFieldRounded tf_nama_produk;
    private jtextfieldrounded.JTextFieldRounded tf_qty_produk;
    // End of variables declaration//GEN-END:variables
}
